import type { LeagueConfig } from '../../types/leagueConfig'

// Default LeagueConfig for new WNBA leagues. Commissioners override any
// field via the CreateLeague wizard. Numbers below are starting points,
// not law — adjust freely.
export const WNBA_LEAGUE_PRESET: LeagueConfig = {
  sport: 'wnba',
  season: {
    year: 2026,
    startDate: '2026-05-11',
    weeks: 13,
  },
  roster: {
    activeSize: 10,
    starterSize: 10,
    irSlots: 3,
    benchAllowed: false,
    maxKeepers: 5,
    redshirtsAllowed: true,
    intStashAllowed: true,
  },
  draft: {
    rounds: 10,
    type: 'snake',
    rookieRounds: 2,
    rookieYearsTracked: 3,
    rookieOrderMethod: 'manual',
    allowAdminOverride: true,
  },
  cap: {
    enabled: true,
    floor: 0,
    base: 1_500_000,
    firstApron: 0,
    secondApron: 0,
    hardCap: 1_500_000,
    tradeDelta: 0,
    penaltyRatePerM: 0,
  },
  fees: {
    buyIn: 50,
    firstApronFee: 0,
    franchiseTagFee: 15,
    redshirtFee: 10,
    activationFee: 25,
    penaltyRatePerM: 0,
  },
  scoring: {
    categories: ['FG%', 'FT%', '3PM', 'PTS', 'REB', 'AST', 'STL', 'BLK', 'A/TO'],
    mode: 'category_record',
  },
  keeper: {
    rookieRoundMap: {
      '1.1-1.3': 4,
      '1.4-1.6': 5,
      '1.7-1.9': 6,
      '1.10-1.12': 7,
      '2.x': 10,
      '3.x': 10,
    },
    advanceRule: 'minus_one',
    fallbackRound: null,
    franchiseTagAllowed: true,
    intStashAllowed: true,
  },
  schedule: {
    tradeDeadlineWeek: 9,
    tradeDeadlineDate: '',
    playoffTeams: 6,
    playoffWeeks: 3,
    playoffByeTeams: 2,
    consolationWeeks: 0,
    combineCup: false,
    combineAllStar: true,
    extendFirstWeek: false,
  },
  prizePool: {
    enabled: true,
    walletEnabled: false,
    zones: {
      boilerThreshold: 300,
      bernieThreshold: 10_000,
      gekkoSplit: [70, 20, 10],
      bernieSplit: [40, 15, 9, 4, 4, 4, 4, 4, 4, 4, 4, 4],
      boilerSmallSplit: [80, 20],
    },
  },
  notifications: {
    telegramEnabled: true,
    emailEnabled: true,
    drafts: true,
    trades: true,
    wagers: true,
  },
}
